site_name: DB Note
site_url: http://127.0.0.1:8000/
theme:
  name: material
  language: zh
  favicon: favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black   
      accent: black   
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to bright mode
  features:
    - navigation.instant
    - navigation.instant.prefetch

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - 目录: index.md
  - 第一章 引言: chap.1.md
  - 第二章 关系模型介绍: chap.2.md
  - 第三章 SQL简介: chap.3.md
  - 第四章 中级SQL: chap.4.md
  - 第五章 高级SQL: chap.5.md
  - 第六章 E-R模型: chap.6.md
  - 第七章: chap.7.md
  - 第八章: chap.8.md
  - 第九章: chap.9.md
  - 第十章 索引: chap.10.md
  - 第十一章 查询处理: chap.11.md
  - 第十二章 查询优化: chap.12.md
  - 第十三章 事务管理: chap.13.md
  - 第十四章 并发控制: chap.14.md
  - 第十五章 恢复系统: chap.15.md
